IF NOT EXISTS (SELECT 1 FROM sys.databases WHERE name = 'HKShop')
BEGIN
    CREATE DATABASE HKShop;
END
GO

USE HKShop;
GO

CREATE TABLE LOAI(
    MALOAI INT IDENTITY(1, 1) PRIMARY KEY,
    TENLOAI NVARCHAR(50) NOT NULL,
    TENLOAIALIAS NVARCHAR(50) NULL,
    MOTA NVARCHAR(MAX) NULL,
    HINH NVARCHAR(MAX) NULL
)
GO

CREATE TABLE HangHoa
(
    MaHH INT IDENTITY(1,1) PRIMARY KEY,
    TenHH NVARCHAR(100) NOT NULL,
    TenAlias NVARCHAR(100) NULL,
    MaLoai INT NOT NULL,
    MoTaDonVi NVARCHAR(50) NULL,
    DonGia DECIMAL(18,2) NULL,
    Hinh NVARCHAR(255) NULL,
    NgaySX DATE NOT NULL,
    GiamGia DECIMAL(5,2) NOT NULL DEFAULT 0,
    LuotMua INT NOT NULL DEFAULT 0,
    MoTa NVARCHAR(MAX) NULL,
    
    CONSTRAINT FK_HangHoa_Loai FOREIGN KEY (MaLoai) REFERENCES Loai(MaLoai)
);
GO

CREATE TABLE NguoiDung
(
    Id INT IDENTITY(1,1) PRIMARY KEY,
    TenDangNhap NVARCHAR(50) NOT NULL UNIQUE,
    MatKhau NVARCHAR(255) NOT NULL,
    VaiTro INT NOT NULL DEFAULT 0,
    HieuLuc BIT NOT NULL DEFAULT 1,
    NgayTao DATETIME NOT NULL DEFAULT GETDATE(),
    RandomKey VARCHAR(50) NULL
);
GO

CREATE TABLE KhachHang
(
    MaKH NVARCHAR(20) NOT NULL PRIMARY KEY,
    UserId INT NOT NULL UNIQUE,
    HoTen NVARCHAR(100) NOT NULL,
    GioiTinh BIT NOT NULL,
    NgaySinh DATE NOT NULL,
    DiaChi NVARCHAR(200) NULL,
    DienThoai NVARCHAR(20) NULL,
    Email NVARCHAR(100) NOT NULL,
    Hinh NVARCHAR(255) NULL,

    CONSTRAINT FK_KhachHang_NguoiDung FOREIGN KEY (UserId) REFERENCES NguoiDung(Id) ON DELETE CASCADE
);
GO

CREATE TABLE NhanVien
(
    MaNV NVARCHAR(50) NOT NULL PRIMARY KEY,
    UserId INT NOT NULL UNIQUE,
    HoTen NVARCHAR(100) NOT NULL,
    Email NVARCHAR(100) NOT NULL,
    DienThoai NVARCHAR(20) NULL,

    CONSTRAINT FK_NhanVien_NguoiDung FOREIGN KEY (UserId) REFERENCES NguoiDung(Id) ON DELETE CASCADE
);
GO

CREATE TABLE HoaDon
(
    MaHD INT IDENTITY(1,1) PRIMARY KEY,
    MaKH NVARCHAR(20) NOT NULL,
    NgayDat DATETIME NOT NULL DEFAULT GETDATE(),
    NgayCan DATE NULL,
    NgayGiao DATE NULL,
    HoTen NVARCHAR(100) NULL,
    DiaChi NVARCHAR(200) NOT NULL,
    CachThanhToan NVARCHAR(50) NOT NULL,
    CachVanChuyen NVARCHAR(50) NOT NULL,
    PhiVanChuyen DECIMAL(18,2) NOT NULL DEFAULT 0,
    MaNV NVARCHAR(50) NULL,
    GhiChu NVARCHAR(500) NULL,

    CONSTRAINT FK_HoaDon_KhachHang FOREIGN KEY (MaKH) REFERENCES KhachHang(MaKH),
    CONSTRAINT FK_HoaDon_NhanVien  FOREIGN KEY (MaNV)  REFERENCES NhanVien(MaNV)
);
GO

CREATE TABLE ChiTietHD
(
    MaCT INT IDENTITY(1,1) PRIMARY KEY,
    MaHD INT NOT NULL,
    MaHH INT NOT NULL,
    DonGia DECIMAL(18,2) NOT NULL,
    SoLuong INT NOT NULL CHECK (SoLuong > 0),
    GiamGia DECIMAL(5,2) NOT NULL DEFAULT 0,

    CONSTRAINT FK_ChiTietHD_HoaDon   FOREIGN KEY (MaHD) REFERENCES dbo.HoaDon(MaHD)   ON DELETE CASCADE,
    CONSTRAINT FK_ChiTietHD_HangHoa  FOREIGN KEY (MaHH) REFERENCES dbo.HangHoa(MaHH)
);
GO

CREATE TABLE Cart
(
    MaCart INT IDENTITY(1,1) PRIMARY KEY,
    MaKH NVARCHAR(20) NOT NULL,
    MaHH INT NOT NULL,
    SoLuong INT NOT NULL CHECK (SoLuong > 0),
    DonGia DECIMAL(18,2) NOT NULL,
    NgayThem DATETIME NOT NULL DEFAULT GETDATE(),

    CONSTRAINT FK_Cart_KhachHang FOREIGN KEY (MaKH) REFERENCES KhachHang(MaKH) ON DELETE CASCADE,
    CONSTRAINT FK_Cart_HangHoa   FOREIGN KEY (MaHH) REFERENCES HangHoa(MaHH),
    CONSTRAINT UQ_Cart_KhachHang_HangHoa UNIQUE (MaKH, MaHH)
);
GO