IF NOT EXISTS (SELECT 1 FROM sys.databases WHERE name = 'HKShop')
BEGIN
    CREATE DATABASE HKShop;
END;
USE HKShop;
GO

CREATE TABLE Category(
    Id INT IDENTITY(1, 1) PRIMARY KEY,
    Name NVARCHAR(50) NOT NULL,
    Description NVARCHAR(MAX) NULL,
    Image NVARCHAR(MAX) NULL
)
GO

CREATE TABLE Product
(
    Id INT IDENTITY(1,1) PRIMARY KEY,
    Name NVARCHAR(100) NOT NULL,
    CategoryId INT NOT NULL,
    UnitDescription NVARCHAR(50) NULL,
    UnitPrice DECIMAL(18,2) NULL,
    Image NVARCHAR(255) NULL,
    CreatedDate DATETIME NOT NULL DEFAULT GETDATE(),
    Discount DECIMAL(5,2) NOT NULL DEFAULT 0,
    Views INT NOT NULL DEFAULT 0,
    Description NVARCHAR(MAX) NULL,

    CONSTRAINT FK_Product_Category FOREIGN KEY (CategoryId) REFERENCES Category(Id)
);
GO

CREATE TABLE AppUser
(
    Id INT IDENTITY(1,1) PRIMARY KEY,
    Username NVARCHAR(50) NOT NULL UNIQUE,
    Password NVARCHAR(255) NOT NULL,
    Role INT NOT NULL DEFAULT 0,
    IsActive BIT NOT NULL DEFAULT 1,
    CreatedDate DATETIME NOT NULL DEFAULT GETDATE(),
    RandomKey VARCHAR(50) NULL
);
GO

CREATE TABLE Customer
(
    Id INT IDENTITY(1,1) PRIMARY KEY,
    UserId INT NOT NULL UNIQUE,
    Fullname NVARCHAR(100) NOT NULL,
    Gender BIT NOT NULL,
    Birthday DATE NOT NULL,
    Address NVARCHAR(200) NULL,
    Phone NVARCHAR(20) NULL,
    Email NVARCHAR(100) NOT NULL,
    Avatar NVARCHAR(255) NULL,

    CONSTRAINT FK_Customer_User FOREIGN KEY (UserId) REFERENCES AppUser(Id) ON DELETE CASCADE
);
GO

CREATE TABLE Employee
(
    Id INT IDENTITY(1,1) PRIMARY KEY,
    UserId INT NOT NULL UNIQUE,
    Fullname NVARCHAR(100) NOT NULL,
    Email NVARCHAR(100) NOT NULL,
    Phone NVARCHAR(20) NULL,

    CONSTRAINT FK_Employee_User FOREIGN KEY (UserId) REFERENCES AppUser(Id) ON DELETE CASCADE
);
GO

CREATE TABLE Invoice
(
    Id INT IDENTITY(1,1) PRIMARY KEY,
    CustomerId INT NOT NULL,
    OrderDate DATETIME NOT NULL DEFAULT GETDATE(),
    ShipmentDate DATE NULL,
    ReceiverName NVARCHAR(100) NULL,
    PhoneNumber NVARCHAR(20) NOT NULL,
    Address NVARCHAR(200) NOT NULL,
    StatusId INT NOT NULL DEFAULT 0,
    PaymentMethod NVARCHAR(50) NOT NULL,
    ShippingMethod NVARCHAR(50) NOT NULL,
    ShippingFee DECIMAL(18,2) NOT NULL DEFAULT 0,
    EmployeeId INT NULL,
    Note NVARCHAR(500) NULL,
    Discount DECIMAL(18,2) NOT NULL DEFAULT 0,
    TotalPrice DECIMAL(18,2) NOT NULL,

    CONSTRAINT FK_Invoice_Customer FOREIGN KEY (CustomerId) REFERENCES Customer(Id),
    CONSTRAINT FK_Invoice_Employee FOREIGN KEY (EmployeeId) REFERENCES Employee(Id)
);
GO

CREATE TABLE DetailInvoice
(
    Id INT IDENTITY(1,1) PRIMARY KEY,
    InvoiceId INT NOT NULL,
    ProductId INT NOT NULL,
    SubPrice DECIMAL(18,2) NOT NULL,
    Quantity INT NOT NULL CHECK (Quantity > 0),

    CONSTRAINT FK_DetailInvoice_Invoice   FOREIGN KEY (InvoiceId) REFERENCES dbo.Invoice(Id)   ON DELETE CASCADE,
    CONSTRAINT FK_DetailInvoice_Product  FOREIGN KEY (ProductId) REFERENCES dbo.Product(Id)
);
GO

CREATE TABLE Cart
(
    Id INT IDENTITY(1,1) PRIMARY KEY,
    CustomerId INT NOT NULL,
    TotalPrice DECIMAL(18,2) NOT NULL,
    
    CONSTRAINT FK_Cart_Customer FOREIGN KEY (CustomerId) REFERENCES Customer(Id) ON DELETE CASCADE,
);
GO

CREATE TABLE DetailCart
(
    Id INT IDENTITY(1,1) PRIMARY KEY,
    CartId INT NOT NULL,
    ProductId INT NOT NULL,
    Quantity INT NOT NULL CHECK (Quantity > 0),
    AddedDate DATETIME NOT NULL DEFAULT GETDATE(),
    SubPrice DECIMAL(18,2) NOT NULL,

    CONSTRAINT FK_DetailCart_Cart FOREIGN KEY (CartId) REFERENCES Cart(Id) ON DELETE CASCADE,
    CONSTRAINT FK_DetailCart_Product FOREIGN KEY (ProductId) REFERENCES Product(Id)
)